# Версия docker-compose
version: "3.7"
# Список наших сервисов (контейнеров)
services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:latest
    # маршрутизируем порты
    ports:
      - "81:80"
      - "443:443"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./dockerData/hosts:/etc/nginx/conf.d
      - ./:/var/www
      - ./dockerData/logs/nginx:/var/log/nginx
    # nginx должен общаться с php контейнером
    links:
      - php
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    image: php:7.4-fpm
    # этот образ будет общаться с mysql
    links:
      - mysql
    # монтируем директорию с проектами
    volumes:
      - ./:/var/www
  mysql:
    image: mysql:5.7.40
    ports:
      - "3306:3306"
    volumes:
      - ./dockerData/etc/mysql:/etc/mysql
      - ./dockerData/logs/mysql:/var/log/mysql
      - ./dockerData/mysql:/var/lib/mysql
      - ./dockerData/mysql-files:/var/lib/mysql-files
#      - ./dockerData/data:/docker-entrypoint-initdb.d
    # задаем пароль для root пользователя
    # заливку дампа сайта и создание пользователя для доступа к базе снаружи будем делать позже
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=test
      - MYSQL_USER=data_test
      - MYSQL_PASSWORD=12345